name: Deploy full-stack-react-project Application
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        environment:
            name: production
            url: ${{ steps.deploy-frontend.outputs.url }}
        steps:
            - uses: actions/checkout@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - uses: google-github-actions/auth@v1
              with:
                  service_account: ${{ secrets.GOOGLECLOUD_SERVICE_ACCOUNT }}
                  credentials_json: ${{ secrets.GOOGLECLOUD_CREDENTIALS }}
            - name: Build and push backend image
              uses: docker/build-push-action@v4
              with:
                  context: ./backend
                  file: ./backend/Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/full-stack-react-project-backend:latest
            - id: deploy-backend
              name: Deploy backend
              uses: google-github-actions/deploy-cloudrun@v1
              with:
                  service: full-stack-react-project-backend
                  image: ${{ secrets.DOCKERHUB_USERNAME }}/full-stack-react-project-backend:latest
                  region: ${{ secrets.GOOGLECLOUD_REGION }}
                  env_vars: |
                      DATABASE_URL=${{ secrets.DATABASE_URL }}
                      JWT_SECRET=${{ secrets.JWT_SECRET }}
                  flags: '--allow-unauthenticated'
            - name: Build and push frontend image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/full-stack-react-project-frontend:latest
                  build-args: |
                      VITE_BACKEND_URL=${{ steps.deploy-backend.outputs.url }}/api/v1
                      NODE_ENV=production
            - id: deploy-frontend
              name: Deploy frontend
              uses: google-github-actions/deploy-cloudrun@v1
              with:
                  service: full-stack-react-project-frontend
                  image: ${{ secrets.DOCKERHUB_USERNAME }}/full-stack-react-project-frontend:latest
                  region: ${{ secrets.GOOGLECLOUD_REGION }}
                  flags: '--port=80 --allow-unauthenticated'
