name: Deploy Blog Application
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        environment:
            name: production
            url: ${{ steps.deploy-frontend.outputs.url }}
        steps:
            - uses: actions/checkout@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Azure CLI Login
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            - name: Build and push backend image
              uses: docker/build-push-action@v4
              with:
                  context: ./backend
                  file: ./backend/Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/blog-backend:latest
            - id: deploy-backend
              name: Deploy backend
              run: |
                  az container create \
                    --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
                    --name blog-backend \
                    --image ${{ secrets.DOCKERHUB_USERNAME }}/blog-backend:latest \
                    --cpu 1 \
                    --memory 1.5 \
                    --registry-login-server index.docker.io \
                    --registry-username ${{ secrets.DOCKERHUB_USERNAME }} \
                    --registry-password ${{ secrets.DOCKERHUB_TOKEN }} \
                    --dns-name-label blog-backend-${{ github.run_id }} \
                    --ports 80
            - name: Build and push frontend image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/blog-frontend:latest
                  build-args: VITE_BACKEND_URL=${{ steps.deploy-backend.outputs.url }}/api/v1
            - id: deploy-frontend
              name: Deploy frontend
              uses: google-github-actions/deploy-cloudrun@v1
              with:
                  service: blog-frontend
                  image: ${{ secrets.DOCKERHUB_USERNAME }}/blog-frontend:latest
                  region: ${{ secrets.GOOGLECLOUD_REGION }}
